### ISSUE TITLE
first i try, error with Hakuba

### ISSUE THREAD

**Issue by balitax** [RoRoche/iOSSwiftStarter#2]
i have some error when open on xcode. i think this is Hakuba bugs.  

<img width="257" alt="screen shot 2016-06-01 at 2 15 15 pm" src="https://cloud.githubusercontent.com/assets/1490342/15701273/657fc7ae-2803-11e6-9639-3afcc30ac55e.png">

<img width="693" alt="screen shot 2016-06-01 at 2 15 52 pm" src="https://cloud.githubusercontent.com/assets/1490342/15701276/681223e0-2803-11e6-8639-e92f2bfb4ab3.png">

**Comment by RoRoche** [comment]
OK. I'll try to fix it as soon as possible.
Having a look at the Hakuba documention (https://github.com/nghialv/Hakuba),
it seems that
- `MYCellModel` has been renamed into `CellModel`
- `MYSelectionHandler` renamed into `SelectionHandler`
- `MYTableViewCell` renamed into `Cell`

Thanks for trying iOSSwiftStarter!
